# Utilisation de l'image officielle Node.js 18 avec gestion ARM pour Mac M1
FROM node:18-alpine AS build

# Définir le répertoire de travail dans le conteneur
WORKDIR /usr/src/app

# Copier uniquement les fichiers nécessaires pour l'installation des dépendances
COPY package*.json ./

# Installer les dépendances (Firebase Functions, Firebase Admin, Joi, dotenv)
RUN npm install --production

# Copier le reste des fichiers source
COPY . .

# Exposer le port pour Firebase Functions Emulator
EXPOSE 5001

# Commande pour maintenir le conteneur actif
CMD ["tail", "-f", "/dev/null"]
