name: wig_swap
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  chewie: 1.8.5
  cloud_firestore: 5.4.4
  cloud_firestore_platform_interface: 6.4.3
  cloud_firestore_web: 4.3.2
  cloud_functions: 5.1.3
  cloud_functions_platform_interface: 5.5.37
  cloud_functions_web: 4.10.2
  collection: 1.18.0
  csslib: ^1.0.0
  device_info_plus: ^11.1.0
  device_info_plus_platform_interface: 7.0.1
  dropdown_button2: 2.3.9
  easy_debounce: ^2.0.3
  equatable: 2.0.5
  fetch_api: 2.2.0
  fetch_client: 1.1.2
  file_picker: ^8.1.3
  firebase_analytics: 11.3.3
  firebase_analytics_platform_interface: 4.2.5
  firebase_analytics_web: 0.5.10+2
  firebase_auth: 5.3.1
  firebase_auth_platform_interface: 7.4.7
  firebase_auth_web: 5.13.2
  firebase_core: 3.6.0
  firebase_core_platform_interface: 5.3.0
  firebase_core_web: 2.18.1
  firebase_messaging: 15.1.3
  firebase_messaging_platform_interface: 4.5.46
  firebase_messaging_web: 3.9.2
  firebase_performance: 0.10.0+8
  firebase_performance_platform_interface: 0.1.4+44
  firebase_performance_web: 0.1.7+2
  firebase_storage: ^12.3.4
  firebase_storage_platform_interface: 5.1.31
  firebase_storage_web: ^3.10.3
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.4.1
  flutter_card_swiper: ^7.0.2
  flutter_plugin_android_lifecycle: ^2.0.23
  flutter_stripe: ^11.2.0
  flutter_stripe_web: ^6.2.0
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  google_sign_in: 6.2.1
  google_sign_in_android: ^6.1.33
  google_sign_in_ios: ^5.7.8
  google_sign_in_platform_interface: 2.4.5
  google_sign_in_web: 0.12.4+2
  html: 0.15.4
  http: 1.2.2
  image_picker: 1.1.2
  image_picker_android: ^0.8.12+17
  image_picker_for_web: ^3.0.6
  image_picker_ios: ^0.8.12+1
  image_picker_linux: 0.2.1+1
  image_picker_macos: 0.2.1+1
  image_picker_platform_interface: 2.10.0
  image_picker_windows: 0.2.1+1
  infinite_scroll_pagination: 4.0.0
  intl: 0.19.0
  json_path: ^0.7.4
  mime_type: ^1.0.1
  page_transition: 2.1.0
  path_provider: 2.1.4
  path_provider_android: ^2.2.12
  path_provider_foundation: 2.4.0
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: ^2.3.0
  permission_handler: 11.3.1
  permission_handler_android: ^12.0.13
  permission_handler_apple: 9.4.5
  permission_handler_html: 0.1.3+2
  permission_handler_platform_interface: 4.2.3
  permission_handler_windows: 0.2.1
  photo_view: 0.15.0
  plugin_platform_interface: 2.1.8
  provider: 6.1.2
  rxdart: ^0.28.0
  shared_preferences: 2.3.2
  shared_preferences_android: ^2.3.3
  shared_preferences_foundation: ^2.5.3
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.2
  shared_preferences_windows: 2.4.1
  sign_in_with_apple: ^6.1.3
  sign_in_with_apple_platform_interface: 1.1.0
  sign_in_with_apple_web: 2.1.0
  simple_gradient_text: ^1.3.0
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.4.0
  sqflite_common: ^2.5.4+5
  stream_transform: 2.1.0
  stripe_android: ^11.2.1
  stripe_ios: ^11.2.0
  stripe_js: ^6.2.0
  stripe_platform_interface: ^11.2.0
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.13
  url_launcher_ios: 6.3.1
  url_launcher_linux: 3.2.0
  url_launcher_macos: 3.2.1
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.3.3
  url_launcher_windows: ^3.1.3
  video_player: ^2.9.2
  video_player_android: ^2.7.15
  video_player_avfoundation: ^2.6.2
  video_player_platform_interface: ^6.2.3
  video_player_web: 2.3.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.2
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

