// Export pages
export '/users/profil/profil_widget.dart' show ProfilWidget;
export '/users/profile08/profile08_widget.dart' show Profile08Widget;
export '/users/create_id_users/create_id_users_widget.dart'
    show CreateIdUsersWidget;
export '/account_profile_creation/auth_2_create/auth2_create_widget.dart'
    show Auth2CreateWidget;
export '/account_profile_creation/auth_2_login/auth2_login_widget.dart'
    show Auth2LoginWidget;
export '/account_profile_creation/auth_2_forgot_password/auth2_forgot_password_widget.dart'
    show Auth2ForgotPasswordWidget;
export '/account_profile_creation/auth_2_create_profile/auth2_create_profile_widget.dart'
    show Auth2CreateProfileWidget;
export '/account_profile_creation/auth_2_profile/auth2_profile_widget.dart'
    show Auth2ProfileWidget;
export '/account_profile_creation/auth_2_edit_profile/auth2_edit_profile_widget.dart'
    show Auth2EditProfileWidget;
export '/products/gallerie_perruques/gallerie_perruques_widget.dart'
    show GalleriePerruquesWidget;
export '/products/detail_product/detail_product_widget.dart'
    show DetailProductWidget;
export '/products/vente_perruque/vente_perruque_widget.dart'
    show VentePerruqueWidget;
export '/products/category_page/category_page_widget.dart'
    show CategoryPageWidget;
export '/products/picture_gallery/picture_gallery_widget.dart'
    show PictureGalleryWidget;
export '/products/grow_up_picture/grow_up_picture_widget.dart'
    show GrowUpPictureWidget;
export '/products/my_list/my_list_widget.dart' show MyListWidget;
export '/offres/faire_une_offre/faire_une_offre_widget.dart'
    show FaireUneOffreWidget;
export '/offres/offres_faites/offres_faites_widget.dart'
    show OffresFaitesWidget;
export '/received_offers/offre_recues/offre_recues_widget.dart'
    show OffreRecuesWidget;
export '/offres/liste_offres_faites/liste_offres_faites_widget.dart'
    show ListeOffresFaitesWidget;
export '/offres/liste_offres_recues/liste_offres_recues_widget.dart'
    show ListeOffresRecuesWidget;
export '/offres/traitement_offre_recue/traitement_offre_recue_widget.dart'
    show TraitementOffreRecueWidget;
export '/products/swipeable_stack/swipeable_stack_widget.dart'
    show SwipeableStackWidget;
export '/chat_groupwbubbles/chat_2_details/chat2_details_widget.dart'
    show Chat2DetailsWidget;
export '/chat_groupwbubbles/chat_2_main/chat2_main_widget.dart'
    show Chat2MainWidget;
export '/chat_groupwbubbles/chat_2_invite_users/chat2_invite_users_widget.dart'
    show Chat2InviteUsersWidget;
export '/chat_groupwbubbles/image_details/image_details_widget.dart'
    show ImageDetailsWidget;
export '/support_ticket/support_ticket_list/support_ticket_list_widget.dart'
    show SupportTicketListWidget;
export '/support_ticket/support_submit_ticket/support_submit_ticket_widget.dart'
    show SupportSubmitTicketWidget;
export '/support_ticket/support_ticket_details/support_ticket_details_widget.dart'
    show SupportTicketDetailsWidget;
export '/products/favorite_swipeable_stack/favorite_swipeable_stack_widget.dart'
    show FavoriteSwipeableStackWidget;
export '/products/gallerie_perruques_copy/gallerie_perruques_copy_widget.dart'
    show GalleriePerruquesCopyWidget;
export '/chat_g_p_t_component/chat_ai_screen/chat_ai_screen_widget.dart'
    show ChatAiScreenWidget;
export '/paiement/dialogue_modal_paiement/dialogue_modal_paiement_widget.dart'
    show DialogueModalPaiementWidget;
export '/home_page_fil_actuality/home_page_fil_actuality_widget.dart'
    show HomePageFilActualityWidget;
export '/fil_actuality/add_page_actuality/add_page_actuality_widget.dart'
    show AddPageActualityWidget;
export '/fil_actuality/post_details/post_details_widget.dart'
    show PostDetailsWidget;
export '/fil_actuality/chatindividuel/chatindividuel_widget.dart'
    show ChatindividuelWidget;
export '/products/id_vendeur/id_vendeur_widget.dart' show IdVendeurWidget;
export '/paiement/paiement_wave/paiement_wave_widget.dart'
    show PaiementWaveWidget;
export '/paiement/paiement_orange/paiement_orange_widget.dart'
    show PaiementOrangeWidget;
export '/paiement/payement_refuse/payement_refuse_widget.dart'
    show PayementRefuseWidget;
export '/paiement/votre_paiement_accepte/votre_paiement_accepte_widget.dart'
    show VotrePaiementAccepteWidget;
